### PR TITLE
#9: Smash all build-level uses of name 'detection' to 'detector'

### LINKED ISSUE #9: Filename mismatch in CMakeLists.txt
The build path creates `detectorTargets.cmake`, while the export path creates `detectionTargets.cmake`. These should be aligned, to avoid confusion.

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #9

### CODE REVIEW

**Review by cz4rs — APPROVED** [review]
looks good to me

**Review by JacobDomagala — APPROVED** [review]

**Comment by PhilMiller** [comment]
Ugh, the vt build breaks with this

**Comment by PhilMiller** [comment]
Ah, I think it dislikes having `checkpoint` under `lib/`, but an explicit path to `detector`

**Comment by PhilMiller** [comment]
If I don't mix how vt gets its dependencies, it's fine.

**Pull request merged**
